/* eslint-disable import/prefer-default-export */
export const resourceList = [
  new URL('@/assets/images/map/map_bed_room.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_kitchen.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_living_room.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_living_room_out.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_home.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_hall_0.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_hall_1.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_hall_2.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_hall_3.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_hall_4.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_hall_5.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_country_0.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_country_1.jpg', import.meta.url).href,
  new URL('@/assets/images/map/map_balcony.jpg', import.meta.url).href,

  new URL('@/assets/images/sprites/mascot_float.png', import.meta.url).href,
  new URL('@/assets/images/sprites/mascot_bye.png', import.meta.url).href,
  new URL('@/assets/images/sprites/mascot_hi.png', import.meta.url).href,
  new URL('@/assets/images/sprites/mascot_talk.png', import.meta.url).href,
  new URL('@/assets/images/sprites/marker.png', import.meta.url).href,
  new URL('@/assets/images/sprites/interactive.png', import.meta.url).href,

  // home
  new URL('@/assets/images/home/logo.png', import.meta.url).href,
  new URL('@/assets/images/home/icon_community.png', import.meta.url).href,
  new URL('@/assets/images/home/icon_country.png', import.meta.url).href,
  new URL('@/assets/images/home/icon_family.png', import.meta.url).href,
  new URL('@/assets/images/home/icon_video.png', import.meta.url).href,

  // family
  new URL('@/assets/images/family/back_button_bg.png', import.meta.url).href,
  new URL('@/assets/images/family/back_button_icon.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_bed_room_0.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_bed_room_1.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_bed_room_2.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_kitchen_0.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_kitchen_1.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_living_room_0.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_living_room_1.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_living_room_2.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_living_room_3.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_living_room_4.png', import.meta.url).href,
  new URL('@/assets/images/family/cover_living_room_5.png', import.meta.url).href,
  new URL('@/assets/images/family/icon_arrow.png', import.meta.url).href,
  new URL('@/assets/images/family/icon_down.png', import.meta.url).href,
  new URL('@/assets/images/family/icon_play.png', import.meta.url).href,
  new URL('@/assets/images/family/poster.png', import.meta.url).href,
];
